// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 手动控制侧边栏，避免本科和研究生同名学院的混淆
  Sidebar: [
    'README',
    {
      type: 'category',
      label: '本科生院',
      link: {
        type: 'generated-index',
        title: '本科生院',
        description: '本科期间的课程资料汇总，涵盖各类专业必修课和选修课。',
        slug: '/undergraduate',
      },
      items: [
        {
          type: 'category',
          label: '大学英语教学部',
          link: {
            type: 'generated-index',
            title: '大学英语教学部',
            description: '大学英语教学部的课程资料汇总',
            slug: '/undergraduate/大学英语教学部',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'undergraduate/大学英语教学部',
            },
          ],
        },
        {
          type: 'category',
          label: '软件工程学院',
          link: {
            type: 'generated-index',
            title: '软件工程学院',
            description: '软件工程学院的课程资料汇总',
            slug: '/undergraduate/软件工程学院',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'undergraduate/软件工程学院',
            },
          ],
        },
        {
          type: 'category',
          label: '数据科学与工程学院',
          link: {
            type: 'generated-index',
            title: '数据科学与工程学院',
            description: '数据科学与工程学院的课程资料汇总',
            slug: '/undergraduate/数据科学与工程学院',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'undergraduate/数据科学与工程学院',
            },
          ],
        },
        {
          type: 'category',
          label: '数学科学学院',
          link: {
            type: 'generated-index',
            title: '数学科学学院',
            description: '数学科学学院的课程资料汇总',
            slug: '/undergraduate/数学科学学院',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'undergraduate/数学科学学院',
            },
          ],
        },
        {
          type: 'category',
          label: '物理学系',
          link: {
            type: 'generated-index',
            title: '物理学系',
            description: '物理学系的课程资料汇总',
            slug: '/undergraduate/物理学系',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'undergraduate/物理学系',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '研究生院',
      link: {
        type: 'generated-index',
        title: '研究生院',
        description: '研究生期间的课程资料汇总，涵盖各类专业必修课和选修课。',
        slug: '/postgraduate',
      },
      items: [
        {
            type: 'category',
            label: '软件工程学院',
            link: {
                type: 'generated-index',
                title: '软件工程学院',
                description: '软件工程学院的课程资料汇总',
                slug: '/postgraduate/软件工程学院',
            },
          items: [
            {
              type: 'autogenerated',
              dirName: 'postgraduate/软件工程',
            },
          ],
        },
        {
            type: 'category',
            label: '计算机科学与技术',
            link: {
                type: 'generated-index',
                title: '计算机科学与技术',
                description: '科研工具参考：https://ecnu.im/d/314',
                slug: '/postgraduate/计算机科学与技术',
            },
          items: [
            {
              type: 'autogenerated',
              dirName: 'postgraduate/计算机科学与技术',
            },
          ],
        },
        {
            type: 'category',
            label: '公共课',
            link: {
                type: 'generated-index',
                title: '公共课',
                description: '公共课的课程资料汇总',
                slug: '/postgraduate/公共课',
            },
          items: [
            {
              type: 'autogenerated',
              dirName: 'postgraduate/公共课',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
